server:
  port: 0

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5600/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbit:
  exchange:
    requestAccount: requestAccount
    receiveAccount: receiveAccount
  queue:
    requestAccount: requestAccount
    receiveAccount: receiveAccount
  key:
    requestAccount: requestAccount
    receiveAccount: receiveAccount

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans