name: bank
version: "0.1"

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - "spring"
  
  consul-importer:
    image: consul-importer:latest
    build:
      context: consul-importer
      dockerfile: Dockerfile
    depends_on:
      - "consul"
    networks:
      - "spring"
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - "spring"
  
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - "spring"

  service-demo1:
    container_name: service-demo1
    build:
      context: service-demo1
      dockerfile: Dockerfile
    image: service-demo1:latest
    depends_on: 
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    ports:
      - "0:8080"
    networks:
      - "spring"

  service-demo2:
    container_name: service-demo2
    build:
      context: service-demo2
      dockerfile: Dockerfile
    image: service-demo2:latest
    depends_on:
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    ports:
      - "0:8080"
    networks:
      - "spring"

  logs:
    container_name: logs
    build:
      context: logs
      dockerfile: Dockerfile
    image: logs:latest
    depends_on:
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    ports:
      - "0:8080"
    networks:
      - "spring"

  gateway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    image: gateway:latest
    depends_on:
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - "spring"

networks:
  spring:
    driver: bridge