server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      enabled: true
    consul:
      config:
        enabled: true
      discovery:
        query-passing: true
    gateway:
      routes:
        - id: frontend
          uri: lb://frontend/
          predicates:
            - Path=/**

        - id: account
          uri: lb://account
          predicates:
            - Path=/account/api/v1/**

        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/api/v1/**

        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/authentication/api/v1/**
        
        - id: demo1
          uri: lb://demo1
          predicates:
            - Path=/demo1/api/v1/**
        
        - id: demo2
          uri: lb://demo2
          predicates:
            - Path=/demo2/api/v1/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans